wandb_version: 1

dataset_name:
  desc: null
  value: '01'
data_root:
  desc: null
  value: /home/aca10131kr/gca50041/quan/Datasets/EEG2fMRI/h5_data/NODDI
work_dir:
  desc: null
  value: /home/aca10131kr/scratch_eeg-to-fmri
num_epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 1.0e-05
alpha:
  desc: null
  value: 0.7
beta:
  desc: null
  value: 0.3
early_stopping_patience:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.43.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1730069646
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.19
      5: 0.17.5
      6: 4.43.3
      8:
      - 5
      13: linux-x86_64
